# Generated by Django 4.2.5 on 2023-09-25 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='job_class',
        ),
    ]
