# Generated by Django 4.2.5 on 2023-09-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_username_employee_job_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_class',
            field=models.CharField(choices=[('orange', 'Oranges'), ('cantaloupe', 'Cantaloupes'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews')], max_length=100),
        ),
    ]
